pipeline {
    agent any

    environment {
        IMAGE_NAME = "shagunkimothi/myapp"
    }

    stages {

        stage('Clone Source') {
            steps {
                git branch: 'main',
                    url: 'git@github.com:shagunkimothi/my-app.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                docker build -t $IMAGE_NAME:latest .
                '''
            }
        }

        stage('Login to Docker Hub') {
            steps {
                withCredentials([string(credentialsId: 'dockerhub-token', variable: 'DOCKER_TOKEN')]) {
                    sh '''
                    echo $DOCKER_TOKEN | docker login -u shagunkimothi --password-stdin
                    '''
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                sh '''
                docker push $IMAGE_NAME:latest
                '''
            }
        }
    }

    post {
        success {
            echo '✅ Build & Push successful!'
        }
        failure {
            echo '❌ Build failed. Check logs.'
        }
    }
}